name: Build and publish Vue
on:
  push:
    branches:
      - main

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - name: build
        run: |
          npm ci
          npm run build
          cd dist
          echo 'analysis.ambalytics.cloud' > CNAME; fi
          git config --global user.email "CI@example.com"
          git config --global user.name "lukasjesche"
          git init
          git add -A
          git commit -m 'deploy'
          git push -f https://}}:${{ secrets.GITHUB_TOKEN }}@github.com/ambalytics/amba-web-analysisfrontend.git master:gh-pages
        shell: bash