# Deploy Vue project to GitHub Pages
name: Deploy

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      # See: https://github.com/actions/setup-node/issues/214#issuecomment-810829250
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: src
        run: |
          cd frontend
      - name: Install dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Upload built
        uses: actions/upload-artifact@v2.2.3
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: [build]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Clear previous build
        run: |
          git rm -r .
      - name: Download built
        uses: actions/download-artifact@v2.0.9
        with:
          name: dist
      - name: Push
        env:
          GIT_NAME: ci
          GIT_EMAIL: ci@ambalytics.com
        run: |
          git config user.name $GIT_NAME
          git config user.email $GIT_EMAIL
          git add .
          git commit -m "deploy"
          git push
